<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Http;

/**
 * Self-host the brand fonts: downloads every woff2 file of the Google Fonts
 * stylesheet below into public/fonts/google/ and writes a local fonts.css
 * (@font-face blocks kept as Google serves them — weights, styles and
 * unicode-range subsets — with URLs pointing at our own files). Pages link
 * /fonts/google/fonts.css instead of fonts.googleapis.com.
 *
 *   php artisan fonts:download          re-run after changing FAMILIES
 */
class DownloadBrandFonts extends Command
{
    protected $signature = 'fonts:download';

    protected $description = 'Download the brand Google Fonts into public/fonts/google (self-hosted)';

    /** The families the app and landing page use (the font variables in resources/css/app.css). */
    public const CSS_URL = 'https://fonts.googleapis.com/css2?family=Abel&family=Baumans&family=Cantarell:ital,wght@0,400;0,700;1,400;1,700&family=Gugi&family=Kodchasan:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,200;1,300;1,400;1,500;1,600;1,700&family=Madimi+One&family=Momo+Trust+Display&family=MuseoModerno:ital,wght@0,100..900;1,100..900&family=Text+Me+One&display=swap';

    /** A modern browser UA so Google serves woff2. */
    private const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

    public function handle(): int
    {
        $dir = public_path('fonts/google');
        File::ensureDirectoryExists($dir);

        $css = Http::withHeaders(['User-Agent' => self::UA])->timeout(30)->get(self::CSS_URL)->throw()->body();

        $saved = [];
        $local = preg_replace_callback('#url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)#', function ($m) use ($dir, &$saved) {
            $url = $m[1];
            // Stable, readable-ish name: family folder + file hash from Google's path.
            $parts = explode('/', parse_url($url, PHP_URL_PATH));
            $family = $parts[2] ?? 'font';
            $file = $family.'-'.substr(sha1($url), 0, 12).'.woff2';
            if (! isset($saved[$file])) {
                if (! is_file("$dir/$file")) {
                    File::put("$dir/$file", Http::withHeaders(['User-Agent' => self::UA])->timeout(30)->get($url)->throw()->body());
                }
                $saved[$file] = true;
            }

            return "url('/fonts/google/{$file}')";
        }, $css);

        File::put("$dir/fonts.css", "/* Self-hosted brand fonts — generated by `php artisan fonts:download`. Do not edit. */\n".$local);

        // Drop files from an earlier run that the stylesheet no longer uses.
        foreach (File::glob("$dir/*.woff2") as $old) {
            if (! isset($saved[basename($old)])) {
                File::delete($old);
            }
        }

        $bytes = collect(array_keys($saved))->sum(fn ($f) => filesize("$dir/$f"));
        $this->info('Saved '.count($saved).' font files ('.round($bytes / 1024).' KB) + fonts.css to public/fonts/google.');

        return self::SUCCESS;
    }
}
