// Generated by Olux Studio at publish time from the extracted design tokens.
export const oluxThemeMap: Record<string, string[]> = {
    "accent": [
        "--color-primary"
    ],
    "text": [
        "--color-default"
    ],
    "navy": [
        "--color-secondary"
    ],
    "font": [
        "--font-default",
        "--font-primary",
        "--font-secondary"
    ]
}
export const oluxThemeDefaults: Record<string, string> = {
    "base_size": "16px",
    "accent": "#f8830f",
    "text": "#222222",
    "navy": "#222222",
    "font": "Poppins"
}
