<?php

namespace App\Services;

use App\Http\Controllers\Api\SiteContentController;
use App\Models\Site;
use Illuminate\Support\Facades\File;

/**
 * Turns a built site into a standalone NUXT 4 APPLICATION:
 * the renderer app (nuxt-template) + the site's full content baked into
 * public/content.json + the site's media files. The app runs on its own
 * (`npm install && npm run dev|generate`) with no CMS behind it.
 *
 * Two exits, one generator:
 *   · publish(): copy the app to the templates staging folder
 *                (/var/www/templates-staging/<site> — host: olux-studio/templates)
 *   · zip():     pack the app for download.
 */
class SiteAppExporter
{
    /** Directories never shipped with a generated app. */
    private const EXCLUDE = ['node_modules', '.nuxt', '.output', 'dist', '.git'];

    /** Generate the standalone app in a working directory; returns its path. */
    public function buildApp(Site $site): string
    {
        $source = base_path('nuxt-template');
        $work = storage_path('app/site-apps/'.$site->name);

        File::deleteDirectory($work);
        File::ensureDirectoryExists($work);

        // 1 · The renderer app source (Nuxt 4), minus build artifacts.
        foreach (File::directories($source) as $dir) {
            if (in_array(basename($dir), self::EXCLUDE, true)) {
                continue;
            }
            File::copyDirectory($dir, $work.'/'.basename($dir));
        }
        foreach (File::files($source, true) as $f) {
            File::copy($f->getPathname(), $work.'/'.$f->getFilename());
        }

        // 2 · Bake the site content: useSiteContent() loads public/content.json
        //     FIRST, so the app is fully standalone — no API required.
        $payload = app(SiteContentController::class)->show($site->name)->getData(true);
        File::ensureDirectoryExists($work.'/public');
        File::put($work.'/public/content.json', json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));

        // 3 · The site's media files — root-relative /storage/media/... URLs
        //     keep working when served from the app's own public dir.
        $media = public_path('storage/media/'.$site->name);
        if (File::isDirectory($media)) {
            File::copyDirectory($media, $work.'/public/storage/media/'.$site->name);
        }

        // 4 · Brand the package.
        $pkgFile = $work.'/package.json';
        if (File::exists($pkgFile)) {
            $pkg = json_decode(File::get($pkgFile), true) ?: [];
            $pkg['name'] = $site->name;
            $pkg['private'] = true;
            File::put($pkgFile, json_encode($pkg, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
        }

        File::put($work.'/README.md', "# {$site->name}\n\nStandalone Nuxt 4 site generated by Olux Studio.\n\n```bash\nnpm install\nnpm run dev       # local preview\nnpm run generate  # static build (dist/)\n```\n\nContent lives in `public/content.json`; media in `public/storage/media/`.\n");

        return $work;
    }

    /** Publish the generated app to the templates staging folder. */
    public function publish(Site $site): string
    {
        $app = $this->buildApp($site);
        $dest = '/var/www/templates-staging/'.$site->name;

        File::deleteDirectory($dest);
        File::ensureDirectoryExists(dirname($dest));
        File::copyDirectory($app, $dest);

        return $dest;
    }

    /** Zip the generated app for download; returns the zip path. */
    public function zip(Site $site): string
    {
        $app = $this->buildApp($site);
        $zipPath = storage_path('app/site-apps/'.$site->name.'.zip');
        File::delete($zipPath);

        $zip = new \ZipArchive();
        if ($zip->open($zipPath, \ZipArchive::CREATE | \ZipArchive::OVERWRITE) !== true) {
            throw new \RuntimeException('Could not create the zip archive.');
        }
        $files = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($app, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::LEAVES_ONLY
        );
        foreach ($files as $file) {
            $rel = $site->name.'/'.ltrim(str_replace($app, '', $file->getPathname()), '/\\');
            $zip->addFile($file->getPathname(), str_replace('\\', '/', $rel));
        }
        $zip->close();

        return $zipPath;
    }
}
