<?php

namespace App\Services;

use App\Models\TemplateSubmission;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

/**
 * Publishes an accepted template submission (a Nuxt app from the staging folder):
 *  1. Copies the staging app → templates/{key} — discovered by TemplateAppRegistry
 *     and copied verbatim per-site by SiteFileGenerator (exact fidelity).
 *  2. Rewrites its block components to consume useOluxContent() so edited content
 *     injects at runtime with the original values as fallbacks (SfcRewriter).
 *  3. Emits a split-file package → resources/templates/{key} so TemplateRegistry /
 *     TemplateService scaffold editable sites (pages → app:{key}:{block} wireframes).
 */
class SubmissionPublisher
{
    /** Build artefacts never copied from staging into the published app. */
    private const EXCLUDE = ['node_modules', '.nuxt', '.output', 'package-lock.json'];

    /** The template's display name — swapped for {site_name} in package nodes. */
    private ?string $manifestName = null;

    public function __construct(private SfcRewriter $rewriter)
    {
    }

    public function publish(TemplateSubmission $submission): void
    {
        $manifest = $submission->extraction;
        if (! $manifest || empty($manifest['pages'])) {
            throw new \RuntimeException("Submission “{$submission->key}” has no extraction manifest — scan it first.");
        }

        $appDir = base_path("templates/{$submission->key}");
        $this->copyApp($submission->stagingPath(), $appDir);

        // Persist the manifest inside the published app — AppBlock resolves block
        // metadata from here. Written explicitly: the copy skips dot-folders.
        File::ensureDirectoryExists("$appDir/.olux");
        File::put("$appDir/.olux/extraction.json", json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));

        $this->rewriter->rewriteApp($appDir, $manifest);

        // Per-template theme bridge: maps site.theme keys onto the template's
        // own CSS custom properties, with the extracted values as defaults. The
        // olux-design plugin injects only user changes, so a pristine site
        // renders pixel-identical to the shipped app.
        [$map, $defaults] = $this->themeMapping($manifest);
        File::put("$appDir/app/olux-theme.ts",
            "// Generated by Olux Studio at publish time from the extracted design tokens.\n"
            .'export const oluxThemeMap: Record<string, string[]> = '.json_encode($map, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n"
            .'export const oluxThemeDefaults: Record<string, string> = '.json_encode($defaults, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n");

        $this->writePackage($manifest);

        // The published template must be a COMPLETE, self-contained copy —
        // pages, block components, styles, scripts, assets, theme, manifest.
        // Fail the publish loudly rather than accept a partial template.
        $this->verifyComplete($submission, $appDir);
    }

    /**
     * Post-publish integrity check: every aspect of the web app must exist in
     * the CMS's own copies, independent of the staging folder.
     *
     * @throws \RuntimeException listing every missing aspect
     */
    private function verifyComplete(TemplateSubmission $submission, string $appDir): void
    {
        $manifest = $submission->extraction;
        $key = $submission->key;
        $missing = [];

        // 1. Pages: every page file from the manifest exists in the copy.
        foreach ($manifest['pages'] as $page) {
            if (! File::exists("$appDir/{$page['file']}")) {
                $missing[] = "page file {$page['file']}";
            }
        }

        // 2. Layout blocks: every block's component file exists and consumes CMS content.
        foreach ($manifest['pages'] as $page) {
            foreach ($page['blocks'] as $block) {
                $file = "$appDir/app/components/{$block['component']}.vue";
                if (! File::exists($file)) {
                    $missing[] = "block component {$block['component']}.vue";
                } elseif (! empty($block['nodes']) && ! str_contains(File::get($file), 'useOluxContent')) {
                    $missing[] = "content wiring in {$block['component']}.vue";
                }
            }
        }

        // 3. Styles & scripts: the app config (fonts/vendor JS/CSS links) + stylesheets.
        if (! File::exists("$appDir/nuxt.config.ts") && ! File::exists("$appDir/nuxt.config.js")) {
            $missing[] = 'nuxt.config (fonts/scripts/styles head)';
        }
        foreach (File::glob($submission->stagingPath().'/public/assets/stylesheets/*.css') as $css) {
            if (! File::exists("$appDir/public/assets/stylesheets/".basename($css))) {
                $missing[] = 'stylesheet '.basename($css);
            }
        }

        // 4. Assets: the copy carries at least as many files as staging (minus builds).
        $count = fn (string $dir) => File::isDirectory("$dir/public/assets") ? count(File::allFiles("$dir/public/assets")) : 0;
        if ($count($appDir) < $count($submission->stagingPath())) {
            $missing[] = 'assets (copy has fewer files than the web app)';
        }

        // 5. Theme & variables: token bridge + manifest + runtime composable.
        foreach (['app/olux-theme.ts', '.olux/extraction.json', 'app/composables/useOluxContent.ts'] as $f) {
            if (! File::exists("$appDir/$f")) {
                $missing[] = $f;
            }
        }

        // 6. Scaffold package: pages JSON for every manifest page + template.json
        //    + the default LAYOUT every page is based on.
        $pkg = resource_path("templates/{$key}");
        if (! File::exists("$pkg/template.json")) {
            $missing[] = 'package template.json';
        }
        if (! File::exists("$pkg/layouts/default.json")) {
            $missing[] = 'package layouts/default.json';
        }
        foreach ($manifest['pages'] as $page) {
            $slug = Str::slug($page['name']) ?: 'home';
            if (! File::exists("$pkg/pages/{$slug}.json")) {
                $missing[] = "package pages/{$slug}.json";
            }
        }

        if ($missing !== []) {
            throw new \RuntimeException(
                "Published template “{$key}” is INCOMPLETE — rejected. Missing: ".implode(' · ', $missing)
            );
        }
    }

    /**
     * Map site.theme keys → the template's CSS custom properties, using name
     * heuristics over the extracted `:root` tokens. Returns [map, defaults].
     *
     * @return array{0: array<string, string[]>, 1: array<string, string>}
     */
    private function themeMapping(array $manifest): array
    {
        $tokens = $manifest['theme'] ?? [];
        $map = [];
        $defaults = ['base_size' => '16px'];

        $match = function (array $needles, string $prefix) use ($tokens): array {
            $vars = [];
            foreach ($tokens as $prop => $value) {
                if (! str_starts_with($prop, $prefix)) {
                    continue;
                }
                foreach ($needles as $n) {
                    if (str_contains($prop, $n)) {
                        $vars["--{$prop}"] = $value;
                        break;
                    }
                }
            }

            return $vars;
        };

        foreach ([
            'accent' => $match(['primary', 'accent'], 'color-'),
            'text'   => $match(['default', 'text'], 'color-'),
            'navy'   => $match(['secondary', 'dark', 'navy'], 'color-'),
        ] as $key => $vars) {
            if ($vars !== []) {
                $map[$key] = array_keys($vars);
                $defaults[$key] = (string) reset($vars);
            }
        }

        // Body font vars (heading fonts keep the template's brand identity).
        $fontVars = [];
        $fontDefault = '';
        foreach ($tokens as $prop => $value) {
            if (str_starts_with($prop, 'font-') && ! str_contains($prop, 'heading')) {
                $fontVars[] = "--{$prop}";
                // "'Poppins', sans-serif" → Poppins
                if ($fontDefault === '' && preg_match("/'([^']+)'|\"([^\"]+)\"|^([A-Za-z][\\w -]*)/", trim($value), $m)) {
                    $fontDefault = trim($m[1] ?: ($m[2] ?? '') ?: ($m[3] ?? ''));
                }
            }
        }
        if ($fontVars !== []) {
            $map['font'] = $fontVars;
            $defaults['font'] = $fontDefault ?: 'inherit';
        }

        return [$map, $defaults];
    }

    /** Copy the staging app, excluding build artefacts. */
    private function copyApp(string $source, string $destination): void
    {
        if (File::isDirectory($destination)) {
            File::deleteDirectory($destination);
        }
        File::ensureDirectoryExists($destination);

        foreach (File::directories($source) as $dir) {
            if (! in_array(basename($dir), self::EXCLUDE, true)) {
                File::copyDirectory($dir, $destination.'/'.basename($dir));
            }
        }
        foreach (File::files($source, true) as $file) {
            if (! in_array($file->getFilename(), self::EXCLUDE, true)) {
                File::copy($file->getPathname(), $destination.'/'.$file->getFilename());
            }
        }
    }

    /** Emit the split-file package TemplateRegistry discovers. */
    private function writePackage(array $manifest): void
    {
        $this->manifestName = $manifest['name'] ?? null;
        $key = $manifest['key'];
        $dir = resource_path("templates/{$key}");
        File::deleteDirectory($dir);
        File::ensureDirectoryExists("$dir/pages");
        File::ensureDirectoryExists("$dir/tokens");
        File::ensureDirectoryExists("$dir/fonts");

        // ── Canonical structure: every page is based on a LAYOUT. The template's
        // chrome (header/nav + footer) becomes the default layout wrapping a
        // content slot; pages carry ONLY their own content blocks.
        File::ensureDirectoryExists("$dir/layouts");
        $chrome = $this->chromeBlocks($manifest);
        $layoutBlocks = [];
        foreach ($chrome['header'] as $b) {
            $layoutBlocks[] = $this->blockDef($key, $b);
        }
        $layoutBlocks[] = ['type' => 'content'];
        foreach ($chrome['footer'] as $b) {
            $layoutBlocks[] = $this->blockDef($key, $b);
        }
        File::put("$dir/layouts/default.json", json_encode([
            'name'   => $manifest['name'].' layout',
            'blocks' => $layoutBlocks,
        ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));

        $slugs = [];
        foreach ($manifest['pages'] as $page) {
            $slug = $page['url'] === '/' ? 'home' : Str::slug(trim($page['url'], '/'));
            $slugs[] = $slug;
            File::put("$dir/pages/{$slug}.json", json_encode($this->pageDef($key, $page), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
        }

        // Seed tokens in site.theme's own keys (accent/text/navy/font) so
        // TemplatePackage::theme() → applyToSite gives every new site the
        // template's real palette — theme injection is then a no-op until the
        // user actually changes something.
        [, $themeDefaults] = $this->themeMapping($manifest);
        $colors = array_intersect_key($themeDefaults, array_flip(['accent', 'text', 'navy']));
        File::put("$dir/tokens/colors.json", json_encode($colors ?: new \stdClass, JSON_PRETTY_PRINT));

        // Body font first — it's what site.theme's `font` key controls.
        $fonts = [];
        $byRole = collect($manifest['fonts'] ?? [])->sortBy(fn ($f) => ($f['role'] ?? '') === 'body' ? 0 : 1)->values();
        foreach ($byRole as $i => $f) {
            $fonts[$i === 0 ? 'primary' : ($i === 1 ? 'secondary' : "extra{$i}")] = ['family' => $f['family']];
        }
        File::put("$dir/fonts/fonts.json", json_encode($fonts ?: new \stdClass, JSON_PRETTY_PRINT));

        // Design VARIABLES (width/size/height/radius…) — every non-color,
        // non-font :root custom property, preserved with its original name.
        $variables = collect($manifest['theme'] ?? [])
            ->reject(fn ($v, $k) => str_starts_with($k, 'color-') || str_starts_with($k, 'font-'))
            ->all();
        File::put("$dir/tokens/variables.json", json_encode($variables ?: new \stdClass, JSON_PRETTY_PRINT));

        $blockTotal = array_sum(array_map(fn ($p) => count($p['blocks']), $manifest['pages']));
        File::put("$dir/template.json", json_encode([
            'key'         => $key,
            'name'        => $manifest['name'],
            'description' => 'Marketplace template — replicates the '.$manifest['name'].' app exactly, with editable content.',
            'category'    => 'Marketplace',
            'accentColor' => $colors['accent'] ?? '#6366f1',
            'author'      => 'Olux Marketplace',
            'version'     => '1.0.0',
            'createdAt'   => now()->toDateString(),
            'tags'        => array_merge(['App'], $manifest['behaviours'] ?? []),
            'features'    => [
                count($manifest['pages']).' page(s) · '.$blockTotal.' content blocks',
                'Pixel-exact replica of the original app',
                'Content, order and visibility editable in Configure',
            ],
            'renderer'    => $key,   // the published Nuxt app under templates/{key}
            'pages'       => $slugs,
        ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    }

    /** Chrome (header/nav + footer) blocks shared across pages — the layout's bones. */
    private function chromeBlocks(array $manifest): array
    {
        $out = ['header' => [], 'footer' => []];
        $seen = [];
        foreach ($manifest['pages'] as $page) {
            foreach ($page['blocks'] as $block) {
                $k = $block['blockKey'];
                if (isset($seen[$k]) || ! $this->isChrome($block)) {
                    continue;
                }
                $seen[$k] = true;
                $out[preg_match('/footer/i', $k) ? 'footer' : 'header'][] = $block;
            }
        }

        return $out;
    }

    /** Whether a manifest block is layout chrome (lives in the layout, not the page). */
    private function isChrome(array $block): bool
    {
        return (bool) preg_match('/header|navbar|nav$|footer/i', $block['blockKey']);
    }

    /** One block definition in the shape TemplateService's scaffolding consumes. */
    private function blockDef(string $templateKey, array $block): array
    {
        // The template's own brand name becomes the {site_name} placeholder so
        // every scaffolded site is branded with ITS name (logo, hero, copyright).
        $brand = $this->manifestName ?? null;

        return [
            'type'  => "app:{$templateKey}:{$block['blockKey']}",
            'name'  => $block['name'],
            'nodes' => array_map(fn ($n) => [
                'label' => $n['label'],
                'type'  => $n['type'],
                'value' => $brand && $n['type'] === 'text'
                    ? str_ireplace($brand, '{site_name}', $n['value'])
                    : $n['value'],
                'order' => $n['order'],
                // Semantic kind (item:icon, html, cta…) → Node.description,
                // so the canvas preview can rank fields by meaning.
                'description' => $n['kind'] ?? '',
            ], $block['nodes']),
        ];
    }

    /** One pages/{slug}.json — CONTENT blocks only; chrome lives in the layout. */
    private function pageDef(string $templateKey, array $page): array
    {
        $brand = $this->manifestName ?? null;

        $blocks = [];
        foreach ($page['blocks'] as $block) {
            if ($this->isChrome($block)) {
                continue;
            }
            $blocks[] = $this->blockDef($templateKey, $block);
        }

        return [
            'name'       => $page['name'],
            'url'        => $page['url'],
            'layout'     => 'default',   // every page is based on a template layout
            'keywords'   => strtolower($page['name']),
            // Page attributes travel with the template (head title today;
            // description/og fields follow the same channel when extracted).
            'attributes' => array_filter([
                'title' => $brand && isset($page['title'])
                    ? str_ireplace($brand, '{site_name}', $page['title'])
                    : ($page['title'] ?? null),
            ]),
            'blocks'     => $blocks,
        ];
    }
}
