// Generated by Olux Studio at publish time from the extracted design tokens.
export const oluxThemeMap: Record<string, string[]> = {
    "accent": [
        "--color-primary"
    ],
    "text": [
        "--color-default"
    ],
    "navy": [
        "--color-secondary"
    ],
    "font": [
        "--font-default",
        "--font-primary"
    ]
}
export const oluxThemeDefaults: Record<string, string> = {
    "base_size": "16px",
    "accent": "#0e7c66",
    "text": "#1f2933",
    "navy": "#123047",
    "font": "Inter"
}
