// Generated by Olux Studio at publish time from the extracted design tokens.
export const oluxThemeMap: Record<string, string[]> = {
    "accent": [
        "--color-primary",
        "--color-accent"
    ],
    "text": [
        "--color-default"
    ],
    "navy": [
        "--color-secondary"
    ],
    "font": [
        "--font-default",
        "--font-secondary",
        "--font-alt-1"
    ]
}
export const oluxThemeDefaults: Record<string, string> = {
    "base_size": "16px",
    "accent": "#ec0470",
    "text": "#3d4650",
    "navy": "#14181d",
    "font": "Text Me One"
}
