// Generated by Olux Studio at publish time from the extracted design tokens.
export const oluxThemeMap: Record<string, string[]> = {
    "accent": [
        "--color-primary",
        "--color-primary-dark",
        "--color-primary-soft"
    ],
    "text": [
        "--color-default"
    ],
    "navy": [
        "--color-primary-dark",
        "--color-secondary"
    ],
    "font": [
        "--font-default",
        "--font-primary"
    ]
}
export const oluxThemeDefaults: Record<string, string> = {
    "base_size": "16px",
    "accent": "#146aa8",
    "text": "#1f2830",
    "navy": "#0e4f80",
    "font": "Jost"
}
