// Generated by Olux Studio at publish time from the extracted design tokens.
export const oluxThemeMap: Record<string, string[]> = {
    "accent": [
        "--color-primary"
    ],
    "text": [
        "--color-default"
    ],
    "navy": [
        "--color-secondary"
    ],
    "font": [
        "--font-default",
        "--font-primary"
    ]
}
export const oluxThemeDefaults: Record<string, string> = {
    "base_size": "16px",
    "accent": "#b08968",
    "text": "#3b3733",
    "navy": "#171412",
    "font": "Roboto"
}
